### ISSUE TITLE
BnP store size

### ISSUE THREAD

**Issue by elad** [voldemort/voldemort#425]
Hello,

I'm using BnP to load a 2.5mb Avro file to a two-node read-only Voldemort cluster. The cluster configuration is taken from `config/readonly_two_nodes_cluster`. I use gzip compression and replication factor of 2. I expect the resulting data size across both nodes to be around 5mb. However, it's 11mb.

What could be the reason for the difference in data size? What am I missing?

**Comment by FelixGV** [comment]
This data growth is expected.

There are various reasons that can affect this, but the main one is that the Avro file in Hadoop can benefit from block-level compression, whereas the Read-Only formatted files can only have record-level compression (which, for certain data sets, does not actually compress at all, in which case, it may be beneficial to turn off compression record altogether). This is because of the nature of the Read-Only format, which is optimized for random look ups rather than large sequential scans.

Moreover, there is a small overhead for the Read-Only index files, which is up to 12 bytes per record (if you use `save.keys=true` in your BnP job, which is the recommended setting). The index's overhead is typically negligible, but for a data set where the key and value sizes are very small, it could be significant.

In some repetitive data sets which compress very well in Avro on Hadoop, we sometimes observe a 10x increase in the Read-Only data size. I would say your 2x data size increase is entirely within the realm of reason.

**Comment by elad** [comment]
> There are various reasons that can affect this, but the main one is that the Avro file in Hadoop can benefit from block-level compression, whereas the Read-Only formatted files can only have record-level compression (which, for certain data sets, does not actually compress at all, in which case, it may be beneficial to turn off compression record altogether). This is because of the nature of the Read-Only format, which is optimized for random look ups rather than large sequential scans.

I figured this would be the reason. Our existing solution seeks directly into Avros so we can maintain block/file-level compression ratios. Works very well with out large chunks of text. Good to know it's not something broken. :)

Thanks!

**Comment by FelixGV** [comment]
> Our existing solution seeks directly into Avros so we can maintain block/file-level compression ratios. Works very well with out large chunks of text.

I'm curious to hear more about the implementation details and performance characteristics of this other solution you're talking about. Is it an open-source or proprietary solution?

Where do you envision Voldemort RO fitting into that? Are you intending it to be a replacement of that other solution or a complementary system for different use cases?

**Comment by elad** [comment]
It's an internal debugging tool we call AvroDB. We will probably release it as open source at some point because it makes it easy to work with and examine Avro files (Hadoop output) before further processing is taking place.

AvroDB assumes the Avros are sorted and keeps an a (small) local index. The Avros themselves are on S3. When access happens, we read the index (fast) to pick up the Avro block offset. We then seek to that address and look for the specific record. Performance isn't a primary requirement; being able to do random access on a large quantity of data is.

We're looking into Voldemort as a replacement for AvroDB in production. While data accessibility works, there are many other things that are missing (redundancy, hot swapping, rebalancing, etc.) and exist in Voldemort. We'd rather direct our efforts towards making Voldemort work for us than develop an entirely in-house solution.

**Comment by FelixGV** [comment]
That's very interesting, actually! It could be nice to plug in this AvroDB as a storage engine for Voldemort. That could be useful for use cases that have large footprint but do not have low latency requirements. We have some of these use cases here which are hard to optimize, cost-wise, on our current set up.

Anyway, it's just wishful thinking. I don't think we have enough of these large footprint latency insensitive use cases to warrant the development cost, even if AvroDB was open-source. Anyhow, it's an interesting idea.

**Comment by elad** [comment]
I'll ping this thread once it's open source just so you guys are aware of it. :)

**Comment by FelixGV** [comment]
Cool, thanks (: !
